config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :plants do
    member do
      patch 'watered'
    end
    collection do
      get 'plants_to_water'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :user
  validates :name, uniqueness: { message: "is already taken" }
  validates :rythm, presence: { message: "veuillez indiquer à quelle frequence arroser cette plante" }
  has_one_attached :photo
  before_save :set_alive

  private

  def set_alive
    self.alive = true
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :plants, dependent: :destroy
  has_one_attached :photo
  validates :username, uniqueness: { message: "is already taken" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo, :username, :last_name, :first_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo, :username, :last_name, :first_name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @user = current_user
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :find_plant, only: [:show, :destroy, :watered]
  def index
    @plants = Plant.where(user: current_user)
  end

  def show
  end

  def new
    @plant = Plant.new
  end

  def create
    @plant = Plant.new(plant_params)
    @plant.user = current_user
    @plant.save!
    redirect_to plant_path(@plant)
  end

  def destroy
    @plant.destroy
    redirect_to plants_path
  end

  def watered
    @plant.update!(next_watered_at: @plant.rythm.days.from_now)
    redirect_to plant_path(@plant)
  end

  def plants_to_water
    @plants = Plant.where(user: current_user, alive: true).where('next_watered_at <= ?', Date.today)
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :rythm, :photo)
  end

  def find_plant
    @plant = Plant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlantWatering</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="content-wrapper">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">

  <h1><%= current_user.username %></h1>

  <%= link_to "Editer mes informations", edit_user_registration_path %>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.rustica.fr/images/xarrosage-shutterstock-1496455001-opti-l760-h550.jpg.pagespeed.ic.vot0uJE0Mm.webp);">
  <div class="container" style="text-align: center;">
    <h1>Le jardinage devient facile meme pour les débutants</h1>
    <p>Plus aucune raison pour que vos plantes meurent</p>
    <%= link_to(plants_path) do%>
      <div class="btn btn-ghost">Mes plantes</div>
    <% end %>
  </div>
</div>

app/views/plants/index.html.erb
<div class="container">
  <h1>Mes Plantes</h1>
  <div class="cards-plants">
    <% @plants.each do |plant| %>
      <div class="card-plant">
        <%= link_to(plant_path(plant)) do %>
          <%= cl_image_tag(plant.photo.key) %>
          <h3><%= plant.name %></h3>
        <% end %>
      </div>
    <% end %>
  </div>

  <p><%= link_to "Ajouter une plante", new_plant_path %></p>
</div>

app/views/plants/new.html.erb
<%= simple_form_for(@plant) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.input :rythm %>
  <%= f.submit "Ajouter une plante"%>
<% end %>

app/views/plants/plants_to_water.html.erb
<div class="container">
  <h1>Au secours, on a soif!</h1>
  <div class="cards-plants">
    <% @plants.each do |plant| %>
      <div class="card-plant">
        <%= link_to(plant_path(plant)) do %>
          <%= cl_image_tag(plant.photo.key) %>
          <h3><%= plant.name %></h3>
        <% end %>
      </div>
    <% end %>
  </div>

app/views/plants/show.html.erb
<h2><%= @plant.name %></h2>
<%= cl_image_tag(@plant.photo.key) %>
<p>Prochain arosage : <%= @plant.next_watered_at %></p>
<% if @plant.alive == true %>
  <%= link_to(watered_plant_path, method: :patch) do%>
      <div class="btn btn-ghost">Arroser <%= @plant.name %></div>
    <% end %>
  <p>Bravo, votre plante est toujours vivante!</p>
  <% else %>
  <p>Dommage, votre plante est morte</p>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/anietchka" target="_blank"><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/anitchka92/?hl=fr" target="_blank"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/nioucha" target="_blank"><i class="fab fa-facebook"></i></a>
    <!--<a href="#"><i class="fab fa-twitter"></i></a>-->
    <a href="https://www.linkedin.com/in/anna-bozio/" target="_blank"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> by Ania
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar sticky">
  <div class="navbar-logo">
    <%= link_to root_path, class: "d-flex justify-content-between align-items-center" do %>
      <%= image_tag "—Pngtree—plant pot_4543569.png" %>
      <p class="text-light ml-2">Easy Tree</p>
    <% end %>
  </div>

  <div class="navbar-menu" id="navbarSupportedContent">
    <div class="nav-title <%= 'active' if current_page?(root_path) %>">
      <%= link_to "Home", root_path %>
    </div>
    <% if user_signed_in? %>
      <div class="nav-title <%= 'active' if current_page?(plants_path) %>">
        <%= link_to "Mes plantes", plants_path %>
      </div>
      <div class="nav-title dropdown">
          <% @user = User.find(current_user[:id]) %>
          <% if @user.photo.key != nil %>
            <%= cl_image_tag @user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "user/default-user-image.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Mon Profil", dashboard_path, class: "dropdown-item " %>
            <%= link_to "Mes plantes à arroser",  plants_to_water_plants_path, class: "dropdown-item " %>
            <%= link_to "Deconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </div>
    <% else %>
      <div class="nav-title <%= 'active' if current_page?(new_user_session_path) %>">
        <%= link_to "Connexion", new_user_session_path %>
      </div>
      <div class="nav-title <%= 'active' if current_page?(new_user_registration_path) %>">
        <%= link_to "Inscription", new_user_registration_path %>
      </div>
    <% end %>
  </div>
</div>